INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (1, 'Seyhan', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (2, 'Ceyhan', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (3, 'Feke', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (4, 'Karaisalı', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (5, 'Karataş', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (6, 'Kozan', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (7, 'Pozantı', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (8, 'Saimbeyli', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (9, 'Tufanbeyli', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (10, 'Yumurtalık', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (11, 'Yüreğir', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (12, 'Aladağ', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (13, 'İmamoğlu', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (14, 'Sarıçam', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (15, 'Çukurova', 1);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (16, 'Adıyaman Merkez', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (17, 'Besni', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (18, 'Çelikhan', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (19, 'Gerger', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (20, 'Gölbaşı / Adıyaman', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (21, 'Kahta', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (22, 'Samsat', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (23, 'Sincik', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (24, 'Tut', 2);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (25, 'Afyonkarahisar Merkez', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (26, 'Bolvadin', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (27, 'Çay', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (28, 'Dazkırı', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (29, 'Dinar', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (30, 'Emirdağ', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (31, 'İhsaniye', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (32, 'Sandıklı', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (33, 'Sinanpaşa', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (34, 'Sultandağı', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (35, 'Şuhut', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (36, 'Başmakçı', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (37, 'Bayat / Afyonkarahisar', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (38, 'İscehisar', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (39, 'Çobanlar', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (40, 'Evciler', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (41, 'Hocalar', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (42, 'Kızılören', 3);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (43, 'Ağrı Merkez', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (44, 'Diyadin', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (45, 'Doğubayazıt', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (46, 'Eleşkirt', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (47, 'Hamur', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (48, 'Patnos', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (49, 'Taşlıçay', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (50, 'Tutak', 4);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (51, 'Amasya Merkez', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (52, 'Göynücek', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (53, 'Gümüşhacıköy', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (54, 'Merzifon', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (55, 'Suluova', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (56, 'Taşova', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (57, 'Hamamözü', 5);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (58, 'Altındağ', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (59, 'Ayaş', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (60, 'Bala', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (61, 'Beypazarı', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (62, 'Çamlıdere', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (63, 'Çankaya', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (64, 'Çubuk', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (65, 'Elmadağ', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (66, 'Güdül', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (67, 'Haymana', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (68, 'Kalecik', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (69, 'Kızılcahamam', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (70, 'Nallıhan', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (71, 'Polatlı', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (72, 'Şereflikoçhisar', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (73, 'Yenimahalle', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (74, 'Gölbaşı / Ankara', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (75, 'Keçiören', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (76, 'Mamak', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (77, 'Sincan', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (78, 'Kazan', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (79, 'Akyurt', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (80, 'Etimesgut', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (81, 'Evren', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (82, 'Pursaklar', 6);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (83, 'Akseki', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (84, 'Alanya', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (85, 'Elmalı', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (86, 'Finike', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (87, 'Gazipaşa', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (88, 'Gündoğmuş', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (89, 'Kaş', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (90, 'Korkuteli', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (91, 'Kumluca', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (92, 'Manavgat', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (93, 'Serik', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (94, 'Demre', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (95, 'İbradı', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (96, 'Kemer / Antalya', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (97, 'Aksu / Antalya', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (98, 'Döşemealtı', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (99, 'Kepez', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (100, 'Konyaaltı', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (101, 'Muratpaşa', 7);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (102, 'Ardanuç', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (103, 'Arhavi', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (104, 'Artvin Merkez', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (105, 'Borçka', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (106, 'Hopa', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (107, 'Şavşat', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (108, 'Yusufeli', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (109, 'Murgul', 8);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (110, 'Bozdoğan', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (111, 'Çine', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (112, 'Germencik', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (113, 'Karacasu', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (114, 'Koçarlı', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (115, 'Kuşadası', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (116, 'Kuyucak', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (117, 'Nazilli', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (118, 'Söke', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (119, 'Sultanhisar', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (120, 'Yenipazar / Aydın', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (121, 'Buharkent', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (122, 'İncirliova', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (123, 'Karpuzlu', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (124, 'Köşk', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (125, 'Didim', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (126, 'Efeler', 9);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (127, 'Ayvalık', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (128, 'Balya', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (129, 'Bandırma', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (130, 'Bigadiç', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (131, 'Burhaniye', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (132, 'Dursunbey', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (133, 'Edremit / Balıkesir', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (134, 'Erdek', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (135, 'Gönen / Balıkesir', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (136, 'Havran', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (137, 'İvrindi', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (138, 'Kepsut', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (139, 'Manyas', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (140, 'Savaştepe', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (141, 'Sındırgı', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (142, 'Susurluk', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (143, 'Marmara', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (144, 'Gömeç', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (145, 'Altıeylül', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (146, 'Karesi', 10);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (147, 'Bilecik Merkez', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (148, 'Bozüyük', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (149, 'Gölpazarı', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (150, 'Osmaneli', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (151, 'Pazaryeri', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (152, 'Söğüt', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (153, 'Yenipazar / Bilecik', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (154, 'İnhisar', 11);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (155, 'Bingöl Merkez', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (156, 'Genç', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (157, 'Karlıova', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (158, 'Kiğı', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (159, 'Solhan', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (160, 'Adaklı', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (161, 'Yayladere', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (162, 'Yedisu', 12);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (163, 'Adilcevaz', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (164, 'Ahlat', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (165, 'Bitlis Merkez', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (166, 'Hizan', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (167, 'Mutki', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (168, 'Tatvan', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (169, 'Güroymak', 13);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (170, 'Bolu Merkez', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (171, 'Gerede', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (172, 'Göynük', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (173, 'Kıbrıscık', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (174, 'Mengen', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (175, 'Mudurnu', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (176, 'Seben', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (177, 'Dörtdivan', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (178, 'Yeniçağa', 14);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (179, 'Ağlasun', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (180, 'Bucak', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (181, 'Burdur Merkez', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (182, 'Gölhisar', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (183, 'Tefenni', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (184, 'Yeşilova', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (185, 'Karamanlı', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (186, 'Kemer / Burdur', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (187, 'Altınyayla / Burdur', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (188, 'Çavdır', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (189, 'Çeltikçi', 15);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (190, 'Gemlik', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (191, 'İnegöl', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (192, 'İznik', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (193, 'Karacabey', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (194, 'Keles', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (195, 'Mudanya', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (196, 'Mustafakemalpaşa', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (197, 'Orhaneli', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (198, 'Orhangazi', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (199, 'Yenişehir / Bursa', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (200, 'Büyükorhan', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (201, 'Harmancık', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (202, 'Nilüfer', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (203, 'Osmangazi', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (204, 'Yıldırım', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (205, 'Gürsu', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (206, 'Kestel', 16);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (207, 'Ayvacık / Çanakkale', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (208, 'Bayramiç', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (209, 'Biga', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (210, 'Bozcaada', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (211, 'Çan', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (212, 'Çanakkale Merkez', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (213, 'Eceabat', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (214, 'Ezine', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (215, 'Gelibolu', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (216, 'Gökçeada', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (217, 'Lapseki', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (218, 'Yenice / Çanakkale', 17);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (219, 'Çankırı Merkez', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (220, 'Çerkeş', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (221, 'Eldivan', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (222, 'Ilgaz', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (223, 'Kurşunlu', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (224, 'Orta', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (225, 'Şabanözü', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (226, 'Yapraklı', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (227, 'Atkaracalar', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (228, 'Kızılırmak', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (229, 'Bayramören', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (230, 'Korgun', 18);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (231, 'Alaca', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (232, 'Bayat / Çorum', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (233, 'Çorum Merkez', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (234, 'İskilip', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (235, 'Kargı', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (236, 'Mecitözü', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (237, 'Ortaköy / Çorum', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (238, 'Osmancık', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (239, 'Sungurlu', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (240, 'Boğazkale', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (241, 'Uğurludağ', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (242, 'Dodurga', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (243, 'Laçin', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (244, 'Oğuzlar', 19);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (245, 'Acıpayam', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (246, 'Buldan', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (247, 'Çal', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (248, 'Çameli', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (249, 'Çardak', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (250, 'Çivril', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (251, 'Güney', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (252, 'Kale / Denizli', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (253, 'Sarayköy', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (254, 'Tavas', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (255, 'Babadağ', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (256, 'Bekilli', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (257, 'Honaz', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (258, 'Serinhisar', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (259, 'Pamukkale', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (260, 'Baklan', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (261, 'Beyağaç', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (262, 'Bozkurt / Denizli', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (263, 'Merkezefendi', 20);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (264, 'Bismil', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (265, 'Çermik', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (266, 'Çınar', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (267, 'Çüngüş', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (268, 'Dicle', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (269, 'Ergani', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (270, 'Hani', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (271, 'Hazro', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (272, 'Kulp', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (273, 'Lice', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (274, 'Silvan', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (275, 'Eğil', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (276, 'Kocaköy', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (277, 'Bağlar', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (278, 'Kayapınar', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (279, 'Sur', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (280, 'Yenişehir / Diyarbakır', 21);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (281, 'Edirne Merkez', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (282, 'Enez', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (283, 'Havsa', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (284, 'İpsala', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (285, 'Keşan', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (286, 'Lalapaşa', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (287, 'Meriç', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (288, 'Uzunköprü', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (289, 'Süloğlu', 22);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (290, 'Ağın', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (291, 'Baskil', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (292, 'Elazığ Merkez', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (293, 'Karakoçan', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (294, 'Keban', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (295, 'Maden', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (296, 'Palu', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (297, 'Sivrice', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (298, 'Arıcak', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (299, 'Kovancılar', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (300, 'Alacakaya', 23);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (301, 'Çayırlı', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (302, 'Erzincan Merkez', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (303, 'İliç', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (304, 'Kemah', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (305, 'Kemaliye', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (306, 'Refahiye', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (307, 'Tercan', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (308, 'Üzümlü', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (309, 'Otlukbeli', 24);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (310, 'Aşkale', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (311, 'Çat', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (312, 'Hınıs', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (313, 'Horasan', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (314, 'İspir', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (315, 'Karayazı', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (316, 'Narman', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (317, 'Oltu', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (318, 'Olur', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (319, 'Pasinler', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (320, 'Şenkaya', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (321, 'Tekman', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (322, 'Tortum', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (323, 'Karaçoban', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (324, 'Uzundere', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (325, 'Pazaryolu', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (326, 'Aziziye', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (327, 'Köprüköy', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (328, 'Palandöken', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (329, 'Yakutiye', 25);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (330, 'Çifteler', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (331, 'Mahmudiye', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (332, 'Mihalıççık', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (333, 'Sarıcakaya', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (334, 'Seyitgazi', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (335, 'Sivrihisar', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (336, 'Alpu', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (337, 'Beylikova', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (338, 'İnönü', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (339, 'Günyüzü', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (340, 'Han', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (341, 'Mihalgazi', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (342, 'Odunpazarı', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (343, 'Tepebaşı', 26);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (344, 'Araban', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (345, 'İslahiye', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (346, 'Nizip', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (347, 'Oğuzeli', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (348, 'Yavuzeli', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (349, 'Şahinbey', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (350, 'Şehitkamil', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (351, 'Karkamış', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (352, 'Nurdağı', 27);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (353, 'Alucra', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (354, 'Bulancak', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (355, 'Dereli', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (356, 'Espiye', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (357, 'Eynesil', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (358, 'Giresun Merkez', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (359, 'Görele', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (360, 'Keşap', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (361, 'Şebinkarahisar', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (362, 'Tirebolu', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (363, 'Piraziz', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (364, 'Yağlıdere', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (365, 'Çamoluk', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (366, 'Çanakçı', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (367, 'Doğankent', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (368, 'Güce', 28);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (369, 'Gümüşhane Merkez', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (370, 'Kelkit', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (371, 'Şiran', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (372, 'Torul', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (373, 'Köse', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (374, 'Kürtün', 29);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (375, 'Çukurca', 30);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (376, 'Hakkari Merkez', 30);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (377, 'Şemdinli', 30);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (378, 'Yüksekova', 30);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (379, 'Altınözü', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (380, 'Dörtyol', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (381, 'Hassa', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (382, 'İskenderun', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (383, 'Kırıkhan', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (384, 'Reyhanlı', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (385, 'Samandağ', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (386, 'Yayladağı', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (387, 'Erzin', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (388, 'Belen', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (389, 'Kumlu', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (390, 'Antakya', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (391, 'Arsuz', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (392, 'Defne', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (393, 'Payas', 31);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (394, 'Atabey', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (395, 'Eğirdir', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (396, 'Gelendost', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (397, 'Isparta Merkez', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (398, 'Keçiborlu', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (399, 'Senirkent', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (400, 'Sütçüler', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (401, 'Şarkikaraağaç', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (402, 'Uluborlu', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (403, 'Yalvaç', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (404, 'Aksu / Isparta', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (405, 'Gönen / Isparta', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (406, 'Yenişarbademli', 32);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (407, 'Anamur', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (408, 'Erdemli', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (409, 'Gülnar', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (410, 'Mut', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (411, 'Silifke', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (412, 'Tarsus', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (413, 'Aydıncık / Mersin', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (414, 'Bozyazı', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (415, 'Çamlıyayla', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (416, 'Akdeniz', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (417, 'Mezitli', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (418, 'Toroslar', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (419, 'Yenişehir / Mersin', 33);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (420, 'Adalar', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (421, 'Bakırköy', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (422, 'Beşiktaş', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (423, 'Beykoz', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (424, 'Beyoğlu', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (425, 'Çatalca', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (426, 'Eyüp', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (427, 'Fatih', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (428, 'Gaziosmanpaşa', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (429, 'Kadıköy', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (430, 'Kartal', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (431, 'Sarıyer', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (432, 'Silivri', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (433, 'Şile', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (434, 'Şişli', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (435, 'Üsküdar', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (436, 'Zeytinburnu', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (437, 'Büyükçekmece', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (438, 'Kağıthane', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (439, 'Küçükçekmece', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (440, 'Pendik', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (441, 'Ümraniye', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (442, 'Bayrampaşa', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (443, 'Avcılar', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (444, 'Bağcılar', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (445, 'Bahçelievler', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (446, 'Güngören', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (447, 'Maltepe', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (448, 'Sultanbeyli', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (449, 'Tuzla', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (450, 'Esenler', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (451, 'Arnavutköy', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (452, 'Ataşehir', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (453, 'Başakşehir', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (454, 'Beylikdüzü', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (455, 'Çekmeköy', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (456, 'Esenyurt', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (457, 'Sancaktepe', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (458, 'Sultangazi', 34);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (459, 'Aliağa', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (460, 'Bayındır', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (461, 'Bergama', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (462, 'Bornova', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (463, 'Çeşme', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (464, 'Dikili', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (465, 'Foça', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (466, 'Karaburun', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (467, 'Karşıyaka', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (468, 'Kemalpaşa / İzmir', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (469, 'Kınık', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (470, 'Kiraz', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (471, 'Menemen', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (472, 'Ödemiş', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (473, 'Seferihisar', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (474, 'Selçuk', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (475, 'Tire', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (476, 'Torbalı', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (477, 'Urla', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (478, 'Beydağ', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (479, 'Buca', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (480, 'Konak', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (481, 'Menderes', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (482, 'Balçova', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (483, 'Çiğli', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (484, 'Gaziemir', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (485, 'Narlıdere', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (486, 'Güzelbahçe', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (487, 'Bayraklı', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (488, 'Karabağlar', 35);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (489, 'Arpaçay', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (490, 'Digor', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (491, 'Kağızman', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (492, 'Kars Merkez', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (493, 'Sarıkamış', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (494, 'Selim', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (495, 'Susuz', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (496, 'Akyaka', 36);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (497, 'Abana', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (498, 'Araç', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (499, 'Azdavay', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (500, 'Bozkurt / Kastamonu', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (501, 'Cide', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (502, 'Çatalzeytin', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (503, 'Daday', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (504, 'Devrekani', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (505, 'İnebolu', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (506, 'Kastamonu Merkez', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (507, 'Küre', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (508, 'Taşköprü', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (509, 'Tosya', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (510, 'İhsangazi', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (511, 'Pınarbaşı / Kastamonu', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (512, 'Şenpazar', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (513, 'Ağlı', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (514, 'Doğanyurt', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (515, 'Hanönü', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (516, 'Seydiler', 37);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (517, 'Bünyan', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (518, 'Develi', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (519, 'Felahiye', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (520, 'İncesu', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (521, 'Pınarbaşı / Kayseri', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (522, 'Sarıoğlan', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (523, 'Sarız', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (524, 'Tomarza', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (525, 'Yahyalı', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (526, 'Yeşilhisar', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (527, 'Akkışla', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (528, 'Talas', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (529, 'Kocasinan', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (530, 'Melikgazi', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (531, 'Hacılar', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (532, 'Özvatan', 38);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (533, 'Babaeski', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (534, 'Demirköy', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (535, 'Kırklareli Merkez', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (536, 'Kofçaz', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (537, 'Lüleburgaz', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (538, 'Pehlivanköy', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (539, 'Pınarhisar', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (540, 'Vize', 39);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (541, 'Çiçekdağı', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (542, 'Kaman', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (543, 'Kırşehir Merkez', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (544, 'Mucur', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (545, 'Akpınar', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (546, 'Akçakent', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (547, 'Boztepe', 40);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (548, 'Gebze', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (549, 'Gölcük', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (550, 'Kandıra', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (551, 'Karamürsel', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (552, 'Körfez', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (553, 'Derince', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (554, 'Başiskele', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (555, 'Çayırova', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (556, 'Darıca', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (557, 'Dilovası', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (558, 'İzmit', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (559, 'Kartepe', 41);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (560, 'Akşehir', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (561, 'Beyşehir', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (562, 'Bozkır', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (563, 'Cihanbeyli', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (564, 'Çumra', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (565, 'Doğanhisar', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (566, 'Ereğli / Konya', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (567, 'Hadim', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (568, 'Ilgın', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (569, 'Kadınhanı', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (570, 'Karapınar', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (571, 'Kulu', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (572, 'Sarayönü', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (573, 'Seydişehir', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (574, 'Yunak', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (575, 'Akören', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (576, 'Altınekin', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (577, 'Derebucak', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (578, 'Hüyük', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (579, 'Karatay', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (580, 'Meram', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (581, 'Selçuklu', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (582, 'Taşkent', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (583, 'Ahırlı', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (584, 'Çeltik', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (585, 'Derbent', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (586, 'Emirgazi', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (587, 'Güneysınır', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (588, 'Halkapınar', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (589, 'Tuzlukçu', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (590, 'Yalıhüyük', 42);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (591, 'Altıntaş', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (592, 'Domaniç', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (593, 'Emet', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (594, 'Gediz', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (595, 'Kütahya Merkez', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (596, 'Simav', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (597, 'Tavşanlı', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (598, 'Aslanapa', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (599, 'Dumlupınar', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (600, 'Hisarcık', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (601, 'Şaphane', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (602, 'Çavdarhisar', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (603, 'Pazarlar', 43);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (604, 'Akçadağ', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (605, 'Arapgir', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (606, 'Arguvan', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (607, 'Darende', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (608, 'Doğanşehir', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (609, 'Hekimhan', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (610, 'Pütürge', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (611, 'Yeşilyurt / Malatya', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (612, 'Battalgazi', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (613, 'Doğanyol', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (614, 'Kale / Malatya', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (615, 'Kuluncak', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (616, 'Yazıhan', 44);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (617, 'Akhisar', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (618, 'Alaşehir', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (619, 'Demirci', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (620, 'Gördes', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (621, 'Kırkağaç', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (622, 'Kula', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (623, 'Salihli', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (624, 'Sarıgöl', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (625, 'Saruhanlı', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (626, 'Selendi', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (627, 'Soma', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (628, 'Turgutlu', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (629, 'Ahmetli', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (630, 'Gölmarmara', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (631, 'Köprübaşı / Manisa', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (632, 'Şehzadeler', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (633, 'Yunusemre', 45);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (634, 'Afşin', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (635, 'Andırın', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (636, 'Elbistan', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (637, 'Göksun', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (638, 'Pazarcık', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (639, 'Türkoğlu', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (640, 'Çağlayancerit', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (641, 'Ekinözü', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (642, 'Nurhak', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (643, 'Dulkadiroğlu', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (644, 'Onikişubat', 46);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (645, 'Derik', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (646, 'Kızıltepe', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (647, 'Mazıdağı', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (648, 'Midyat', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (649, 'Nusaybin', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (650, 'Ömerli', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (651, 'Savur', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (652, 'Dargeçit', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (653, 'Yeşilli', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (654, 'Artuklu', 47);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (655, 'Bodrum', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (656, 'Datça', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (657, 'Fethiye', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (658, 'Köyceğiz', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (659, 'Marmaris', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (660, 'Milas', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (661, 'Ula', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (662, 'Yatağan', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (663, 'Dalaman', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (664, 'Ortaca', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (665, 'Kavaklıdere', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (666, 'Menteşe', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (667, 'Seydikemer', 48);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (668, 'Bulanık', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (669, 'Malazgirt', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (670, 'Muş Merkez', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (671, 'Varto', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (672, 'Hasköy', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (673, 'Korkut', 49);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (674, 'Avanos', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (675, 'Derinkuyu', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (676, 'Gülşehir', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (677, 'Hacıbektaş', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (678, 'Kozaklı', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (679, 'Nevşehir Merkez', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (680, 'Ürgüp', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (681, 'Acıgöl', 50);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (682, 'Bor', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (683, 'Çamardı', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (684, 'Niğde Merkez', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (685, 'Ulukışla', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (686, 'Altunhisar', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (687, 'Çiftlik', 51);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (688, 'Akkuş', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (689, 'Aybastı', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (690, 'Fatsa', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (691, 'Gölköy', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (692, 'Korgan', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (693, 'Kumru', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (694, 'Mesudiye', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (695, 'Perşembe', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (696, 'Ulubey / Ordu', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (697, 'Ünye', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (698, 'Gülyalı', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (699, 'Gürgentepe', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (700, 'Çamaş', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (701, 'Çatalpınar', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (702, 'Çaybaşı', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (703, 'İkizce', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (704, 'Kabadüz', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (705, 'Kabataş', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (706, 'Altınordu', 52);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (707, 'Ardeşen', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (708, 'Çamlıhemşin', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (709, 'Çayeli', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (710, 'Fındıklı', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (711, 'İkizdere', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (712, 'Kalkandere', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (713, 'Pazar / Rize', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (714, 'Rize Merkez', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (715, 'Güneysu', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (716, 'Derepazarı', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (717, 'Hemşin', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (718, 'İyidere', 53);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (719, 'Akyazı', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (720, 'Geyve', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (721, 'Hendek', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (722, 'Karasu', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (723, 'Kaynarca', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (724, 'Sapanca', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (725, 'Kocaali', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (726, 'Pamukova', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (727, 'Taraklı', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (728, 'Ferizli', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (729, 'Karapürçek', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (730, 'Söğütlü', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (731, 'Adapazarı', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (732, 'Arifiye', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (733, 'Erenler', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (734, 'Serdivan', 54);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (735, 'Alaçam', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (736, 'Bafra', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (737, 'Çarşamba', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (738, 'Havza', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (739, 'Kavak', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (740, 'Ladik', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (741, 'Terme', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (742, 'Vezirköprü', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (743, 'Asarcık', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (744, '19 Mayıs', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (745, 'Salıpazarı', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (746, 'Tekkeköy', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (747, 'Ayvacık / Samsun', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (748, 'Yakakent', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (749, 'Atakum', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (750, 'Canik', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (751, 'İlkadım', 55);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (752, 'Baykan', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (753, 'Eruh', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (754, 'Kurtalan', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (755, 'Pervari', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (756, 'Siirt Merkez', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (757, 'Şirvan', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (758, 'Tillo', 56);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (759, 'Ayancık', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (760, 'Boyabat', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (761, 'Durağan', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (762, 'Erfelek', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (763, 'Gerze', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (764, 'Sinop Merkez', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (765, 'Türkeli', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (766, 'Dikmen', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (767, 'Saraydüzü', 57);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (768, 'Divriği', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (769, 'Gemerek', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (770, 'Gürün', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (771, 'Hafik', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (772, 'İmranlı', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (773, 'Kangal', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (774, 'Koyulhisar', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (775, 'Sivas Merkez', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (776, 'Suşehri', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (777, 'Şarkışla', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (778, 'Yıldızeli', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (779, 'Zara', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (780, 'Akıncılar', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (781, 'Altınyayla / Sivas', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (782, 'Doğanşar', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (783, 'Gölova', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (784, 'Ulaş', 58);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (785, 'Çerkezköy', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (786, 'Çorlu', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (787, 'Hayrabolu', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (788, 'Malkara', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (789, 'Muratlı', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (790, 'Saray / Tekirdağ', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (791, 'Şarköy', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (792, 'Marmaraereğlisi', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (793, 'Ergene', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (794, 'Kapaklı', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (795, 'Süleymanpaşa', 59);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (796, 'Almus', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (797, 'Artova', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (798, 'Erbaa', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (799, 'Niksar', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (800, 'Reşadiye', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (801, 'Tokat Merkez', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (802, 'Turhal', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (803, 'Zile', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (804, 'Pazar / Tokat', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (805, 'Yeşilyurt / Tokat', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (806, 'Başçiftlik', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (807, 'Sulusaray', 60);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (808, 'Akçaabat', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (809, 'Araklı', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (810, 'Arsin', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (811, 'Çaykara', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (812, 'Maçka', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (813, 'Of', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (814, 'Sürmene', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (815, 'Tonya', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (816, 'Vakfıkebir', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (817, 'Yomra', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (818, 'Beşikdüzü', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (819, 'Şalpazarı', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (820, 'Çarşıbaşı', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (821, 'Dernekpazarı', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (822, 'Düzköy', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (823, 'Hayrat', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (824, 'Köprübaşı / Trabzon', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (825, 'Ortahisar', 61);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (826, 'Çemişgezek', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (827, 'Hozat', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (828, 'Mazgirt', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (829, 'Nazımiye', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (830, 'Ovacık / Tunceli', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (831, 'Pertek', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (832, 'Pülümür', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (833, 'Tunceli Merkez', 62);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (834, 'Akçakale', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (835, 'Birecik', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (836, 'Bozova', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (837, 'Ceylanpınar', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (838, 'Halfeti', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (839, 'Hilvan', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (840, 'Siverek', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (841, 'Suruç', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (842, 'Viranşehir', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (843, 'Harran', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (844, 'Eyyübiye', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (845, 'Haliliye', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (846, 'Karaköprü', 63);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (847, 'Banaz', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (848, 'Eşme', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (849, 'Karahallı', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (850, 'Sivaslı', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (851, 'Ulubey / Uşak', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (852, 'Uşak Merkez', 64);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (853, 'Başkale', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (854, 'Çatak', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (855, 'Erciş', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (856, 'Gevaş', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (857, 'Gürpınar', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (858, 'Muradiye', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (859, 'Özalp', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (860, 'Bahçesaray', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (861, 'Çaldıran', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (862, 'Edremit / Van', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (863, 'Saray / Van', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (864, 'İpekyolu', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (865, 'Tuşba', 65);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (866, 'Akdağmadeni', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (867, 'Boğazlıyan', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (868, 'Çayıralan', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (869, 'Çekerek', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (870, 'Sarıkaya', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (871, 'Sorgun', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (872, 'Şefaatli', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (873, 'Yerköy', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (874, 'Yozgat Merkez', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (875, 'Aydıncık / Yozgat', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (876, 'Çandır', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (877, 'Kadışehri', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (878, 'Saraykent', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (879, 'Yenifakılı', 66);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (880, 'Çaycuma', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (881, 'Devrek', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (882, 'Ereğli / Zonguldak', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (883, 'Zonguldak Merkez', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (884, 'Alaplı', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (885, 'Gökçebey', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (886, 'Kilimli', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (887, 'Kozlu', 67);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (888, 'Aksaray Merkez', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (889, 'Ortaköy / Aksaray', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (890, 'Ağaçören', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (891, 'Güzelyurt', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (892, 'Sarıyahşi', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (893, 'Eskil', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (894, 'Gülağaç', 68);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (895, 'Bayburt Merkez', 69);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (896, 'Aydıntepe', 69);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (897, 'Demirözü', 69);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (898, 'Ermenek', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (899, 'Karaman Merkez', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (900, 'Ayrancı', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (901, 'Kazımkarabekir', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (902, 'Başyayla', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (903, 'Sarıveliler', 70);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (904, 'Delice', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (905, 'Keskin', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (906, 'Kırıkkale Merkez', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (907, 'Sulakyurt', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (908, 'Bahşili', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (909, 'Balışeyh', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (910, 'Çelebi', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (911, 'Karakeçili', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (912, 'Yahşihan', 71);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (913, 'Batman Merkez', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (914, 'Beşiri', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (915, 'Gercüş', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (916, 'Kozluk', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (917, 'Sason', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (918, 'Hasankeyf', 72);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (919, 'Beytüşşebap', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (920, 'Cizre', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (921, 'İdil', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (922, 'Silopi', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (923, 'Şırnak Merkez', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (924, 'Uludere', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (925, 'Güçlükonak', 73);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (926, 'Bartın Merkez', 74);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (927, 'Kurucaşile', 74);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (928, 'Ulus', 74);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (929, 'Amasra', 74);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (930, 'Ardahan Merkez', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (931, 'Çıldır', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (932, 'Göle', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (933, 'Hanak', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (934, 'Posof', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (935, 'Damal', 75);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (936, 'Aralık', 76);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (937, 'Iğdır Merkez', 76);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (938, 'Tuzluca', 76);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (939, 'Karakoyunlu', 76);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (940, 'Yalova Merkez', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (941, 'Altınova', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (942, 'Armutlu', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (943, 'Çınarcık', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (944, 'Çiftlikköy', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (945, 'Termal', 77);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (946, 'Eflani', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (947, 'Eskipazar', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (948, 'Karabük Merkez', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (949, 'Ovacık / Karabük', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (950, 'Safranbolu', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (951, 'Yenice / Karabük', 78);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (952, 'Kilis Merkez', 79);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (953, 'Elbeyli', 79);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (954, 'Musabeyli', 79);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (955, 'Polateli', 79);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (956, 'Bahçe', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (957, 'Kadirli', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (958, 'Osmaniye Merkez', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (959, 'Düziçi', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (960, 'Hasanbeyli', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (961, 'Sumbas', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (962, 'Toprakkale', 80);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (963, 'Akçakoca', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (964, 'Düzce Merkez', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (965, 'Yığılca', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (966, 'Cumayeri', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (967, 'Gölyaka', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (968, 'Çilimli', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (969, 'Gümüşova', 81);
INSERT INTO Ilce ([ilce_id], [isim], [sehir_id]) VALUES (970, 'Kaynaşlı', 81);